sudo: false
language: node_js
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - node
  - lts/*
before_install:
  - yarn global add codecov
script:
  - yarn test:ci
after_success:
  - yarn semantic-release
  - codecov
