sudo: false
language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - node
  - lts/*
before_install:
  - npm i -g npm@^5.0.0
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
  - bash <(curl -s https://codecov.io/bash)
