sudo: false
language: node_js
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - node
  - lts/*
before_script:
  - npm prune
script:
  - yarn test
after_success:
  - yarn semantic-release
  - bash <(curl -s https://codecov.io/bash)
