sudo: false
language: node_js
notifications:
  email: false
cache:
  yarn: true
node_js:
  - node
  - lts/*
before_install:
  - npm install -g codecov npm@latest
script:
  - npm run test:ci
after_success:
  - npm run semantic-release
  - codecov
